mozilla-releng/scriptworker

CHANGELOG.md
scriptworker/config.py
scriptworker/log.py
scriptworker/poll.py
scriptworker/task.py
scriptworker/utils.py
scriptworker/version.py
setup.cfg
tests/test_config.py
tests/test_log.py
tests/test_task.py
tests/test_utils.py
tox.ini
version.json

I think we're [close to] ready for a 0.3.0 release; PR for that.

0.3.0 release

---

tox.ini

maybe you're not comfortable with my aggressive *s 😄 
I can be more explicit if you are paranoid

tells flake to ignore files in egg based dirs

---

CHANGELOG.md
scriptworker/client.py
scriptworker/config.py
scriptworker/constants.py
scriptworker/exceptions.py
scriptworker/task.py
scriptworker/test/__init__.py
scriptworker/test/data/check_pubkeys.py
scriptworker/test/test_config.py
scriptworker/test/test_context.py
scriptworker/test/test_cot.py
scriptworker/test/test_gpg.py
scriptworker/test/test_integration.py
scriptworker/test/test_task.py
scriptworker/test/test_utils.py
scriptworker/test/test_worker.py
scriptworker/utils.py
scriptworker/worker.py
tox.ini

ports download_artifacts and download_file to scriptworker

---

scriptworker/constants.py
scriptworker/cot/verify.py
scriptworker/test/test_cot_verify.py
scriptworker/test/test_worker.py
scriptworker/worker.py

This should fix #39.  This branch is based on #40.

gpg nuke+mv

---

scriptworker/config.py
scriptworker/test/test_config.py
tempfile

Bugfix for bug 1330395 recursive freezevalues and unfreezevalues

---

CHANGELOG.md
scriptworker/config.py
scriptworker/constants.py
scriptworker/test/__init__.py
scriptworker/test/test_config.py
scriptworker/test/test_integration.py

These replace `freeze_values` and `unfreeze_values`.  Fixes #63 .
@JohanLorenzo this should address your review comments from #61.

`get_frozen_copy` and `get_unfrozen_copy`

---

scriptworker/constants.py

Preparing this cleanup for when the time comes.

Bug 1341352 - cleanup/add new format for balrog scopes. r=aki

---

scriptworker/cot/verify.py
scriptworker/test/test_cot_verify.py

CoT verify: Support both types of artifacts in task payloads

---

CHANGELOG.md
scriptworker/artifacts.py
scriptworker/task.py
scriptworker/test/test_task.py
scriptworker/test/test_worker.py
scriptworker/version.py
scriptworker/worker.py
version.json

Fixes #140 and #139. I had a hard time following which tasks were recently run on signing-linux-dev1; this should help.

add `work_dir/current_task_info.json`. also upload `.diff` files as text/plain

---

scriptworker/artifacts.py
scriptworker/cot/verify.py
scriptworker/test/test_artifacts.py
scriptworker/test/test_cot_verify.py
scriptworker/test/test_utils.py
scriptworker/utils.py

It's unit-tested, but I'd like to test the integration with pushapkscript before asking a formal review.

Bug 1385401 - Support optional upstreamArtifact

---

scriptworker.yaml.tmpl
scriptworker/constants.py
scriptworker/cot/verify.py
scriptworker/task.py
scriptworker/test/__init__.py
scriptworker/test/test_cot_verify.py
scriptworker/test/test_task.py

Add support for verifying comm-central based decision tasks.

---

scriptworker/worker.py

We should sleep if we get no tasks returned from claim_work

---

scriptworker/constants.py
scriptworker/cot/verify.py
scriptworker/test/test_cot_verify.py

Modeled after #181. I reorganized the scopes by alphabetical/tree order.
cc @MihaiTabara

Bug 1433459: Add bouncer support

---

CHANGELOG.md
scriptworker/client.py
scriptworker/test/__init__.py
scriptworker/test/test_client.py
scriptworker/utils.py
scriptworker/version.py
version.json

Follow up #195. Mainly, from discussion in https://github.com/mozilla-releng/signingscript/pull/47#pullrequestreview-103124279

Factorize functions in *script part 2

---

scriptworker/constants.py
scriptworker/cot/verify.py
scriptworker/test/test_cot_verify.py

Bug 1447263 - Add push-snap support

---

CHANGELOG.md
scriptworker/constants.py
scriptworker/cot/verify.py
scriptworker/test/test_cot_verify.py
scriptworker/version.py
version.json

~~**Do not merge yet**~~ Ready to land!

Support mozilla-mobile chains

---

scriptworker/client.py
scriptworker/exceptions.py
scriptworker/gpg.py
scriptworker/test/test_client.py

Aki, I made your changes but this is still broken - tox is barfing. Going to try to look into that

Remove traceback

---

README.rst

drop the trailing close paren ) so the link doesn't 404

readme: fix link to DEFAULT_CONFIG

---

CHANGELOG.md
README.rst
requirements-test-dev.txt
scriptworker/constants.py
scriptworker/task.py
scriptworker/test/__init__.py
scriptworker/test/test_cot_verify.py
scriptworker/test/test_integration.py
scriptworker/test/test_task.py
scriptworker/test/test_utils.py
scriptworker/test/test_worker.py
scriptworker/utils.py
scriptworker/worker.py
tox.ini

Fixes #42. Also fixes #128, #167, #197.
I cleaned up the patchset and split out the patches into logical chunks; hopefully this makes things easier to review.

Add user-cancel support

---

CHANGELOG.md
scriptworker/constants.py
scriptworker/version.py
version.json

Found while testing https://github.com/mozilla-mobile/android-components/pull/1049

Bug 1486089 - part 2: Whitelist android-components and reference-browser repos

---

docs/new_instance.md

@mitchhentges had some observations regarding the docs being unclear whether last section makes sense or not. I agree, the naming was not ideal. Let's fix it.

Fix new_instance docs to ease understanding.

---

scriptworker/cot/verify.py
scriptworker/test/__init__.py
scriptworker/test/test_cot_verify.py

Json-e followup

---

scriptworker/cot/verify.py

This is pretty much the patch you suggested in https://bugzilla.mozilla.org/show_bug.cgi?id=1517201.  I would have used --author=you but I didn't want to blame you for the comment :)

Bug 1517201 - support reading action.extra.actionPerm

---

CHANGELOG.md
scriptworker/constants.py
scriptworker/cot/verify.py
scriptworker/test/test_cot_verify.py
scriptworker/test/test_task.py
scriptworker/version.py
version.json

Discovered in https://github.com/mozilla-mobile/android-components/pull/1284#pullrequestreview-173430757

Bug 1512631 - Enable mozilla-mobile staging release from Github forks

---

docs/new_instance.md

Tiny patch to make the syntax consistent.

Syntax consistency.

---

scriptworker/artifacts.py
scriptworker/test/__init__.py
scriptworker/test/test_artifacts.py
scriptworker/test/test_config.py

Fixes #305.
Also addresses a test failure if the working directory was the root of the repository

Portable mimetypes tests

---

CHANGELOG.md
scriptworker/cot/verify.py
scriptworker/github.py
scriptworker/test/test_cot_verify.py
scriptworker/test/test_github.py
version.json

Failed with https://tools.taskcluster.net/groups/P23yrwGkT4uCNTDA2Rgk5Q/tasks/H_YwIgEAQQO6vBCKjZtPjQ/runs/0/logs/public%2Flogs%2Fchain_of_trust.log#L180 when I tested https://github.com/mozilla-mobile/reference-browser/pull/661

Bug 1533791 - Support "assume" scopes on GitHub repos

---

scriptworker/cot/verify.py
scriptworker/test/test_cot_verify.py
scriptworker/utils.py

also use setdefault in add_enumerable_item_to_dict
fixes #321

make paths unique in get_all_artifacts_per_task_id

---

CHANGELOG.md
scriptworker/constants.py
scriptworker/cot/verify.py
scriptworker/test/test_cot_verify.py
version.json

Initially we thought of considering this as `mobile` but it's not quite a mobile product. Nor is a gecko one, hence for now it's its own thing.

Bug 1536079 - enable scriptworker support for appservices

---

CHANGELOG.md
scriptworker/cot/verify.py
scriptworker/test/test_cot_verify.py
version.json

CoT: Do no use Github's committer data if it's 'web-flow'

---

CHANGELOG.md
scriptworker/github.py
scriptworker/test/test_github.py
scriptworker/version.py
version.json

It should fix https://github.com/mozilla-releng/scriptworker/issues/331

Cache has_commit_landed_on_repository results

---

CHANGELOG.md
scriptworker/context.py
scriptworker/task.py

add TASK_ID to task env.

---

CHANGELOG.md
scriptworker/constants.py
version.json

I'm working on adding staging support for `application-services`, and I'd like to test against my repo, just like I do for mobile repos

Adds mitchhentges as an allowed user to run staging application-services tasks

---

scriptworker/cot/verify.py
scriptworker/test/test_cot_verify.py
setup.py

add create_test_workdir entrypoint

---

CHANGELOG.md
requirements/base.py36.txt
requirements/base.txt
requirements/test.py36.txt
requirements/test.txt
scriptworker/constants.py
scriptworker/cot/verify.py
scriptworker/task.py
scriptworker/test/test_cot_verify.py
scriptworker/test/test_integration.py
scriptworker/version.py
version.json

This is built on top of #379 .
Start using the new workerPoolId format per https://github.com/taskcluster/taskcluster-rfcs/blob/master/rfcs/0145-workerpoolid-taskqueueid.md
Fixes #378

Worker pool

---

CHANGELOG.md
scriptworker/cot/verify.py
scriptworker/github.py
scriptworker/test/test_cot_verify.py
scriptworker/test/test_github.py
scriptworker/test/test_utils.py
scriptworker/utils.py

Retry Github Requests

---

CHANGELOG.md
README.rst
scriptworker/constants.py
scriptworker/test/test_integration.py
scriptworker/test/test_production.py
scriptworker/version.py
version.json

We shouldn't land and release this til Saturday.

switch default taskcluster_root_url to firefox-ci

---

setup.py
tox.ini

Seen in #420: https://firefox-ci-tc.services.mozilla.com/tasks/c0Xp0lqNRlWAmkp_-P8tAw/runs/1/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2Fc0Xp0lqNRlWAmkp_-P8tAw%2Fruns%2F1%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L1397 
Root cause is https://github.com/z4r/python-coveralls/issues/73

Pin coverage to <5

---

HISTORY.rst
src/scriptworker/github.py
src/scriptworker/utils.py
src/scriptworker/version.py
tests/test_github.py
tests/test_utils.py
version.json

Fixes https://github.com/mozilla-releng/scriptworker/issues/419. What do you think @escapewindow?

Make scriptworker retry more whenever CoT fails to connect to Github

---

mypi.ini
src/scriptworker/client.py
src/scriptworker/constants.py
src/scriptworker/log.py
src/scriptworker/utils.py

This is currently WIP ontop of #425

Add more typing support

---

HISTORY.rst
src/scriptworker/constants.py
src/scriptworker/version.py
version.json

bug 1613800 - mark old docker-worker cot key invalid

---

mypi.ini
src/scriptworker/context.py
src/scriptworker/utils.py
tests/test_context.py
tox.ini

Took a stab at adding some more typing to scriptworker.

Add typing to context.py

---

mypi.ini
src/scriptworker/constants.py

Don't check untyped calls in constants because of immuteabledict

---

.taskcluster.yml
pyproject.toml
setup.py
tox.ini

drop py36; add py39

---

pyproject.toml
readthedocs.yml

possibly fix rtd

---

HISTORY.rst
docs/releases.md
src/scriptworker/version.py
version.json

In reality, bumping any part of the version should be fine, but this seems most correct?

Scriptworker 40.0.0

---

HISTORY.rst
docs/cot_overview.rst
src/scriptworker/cot/verify.py
src/scriptworker/version.py
tests/data/cotv4/action_relpro.json
tests/test_cot_verify.py
version.json

Drop non-hook action support in CoT

---

README.rst
src/scriptworker/constants.py
tests/test_cot_verify.py

Opened #522 as a fork to avoid the TC error, but removed the autograph format scope as requested.

Add focus changes

---

src/scriptworker/constants.py

RELENG-847 add mozilla vpn apk release scope to restricted scopes

RELENG-847 add mozilla vpn apk release scope to restricted scopes

---

HISTORY.rst
src/scriptworker/version.py
version.json

42.2.0 version bump

---

src/scriptworker/constants.py

Bug 1766928 - Add mozilla-esr102 to CoT

---

src/scriptworker/constants.py

Add beetmover:bucket:release to mozillavpn cot_restricted_scopes

Add beetmover:bucket:release to mozillavpn cot_restricted_scopes

---

HISTORY.rst
src/scriptworker/version.py
tests/test_production.py
version.json

scriptworker 43.4.0

---

HISTORY.rst
src/scriptworker/constants.py
src/scriptworker/cot/verify.py
src/scriptworker/task.py
tests/test_cot_verify.py
tests/test_task.py

Depends on https://phabricator.services.mozilla.com/D155083

Bug 1784232 - Let CoT support BASE_REF and BASE_REV

---

HISTORY.rst
src/scriptworker/version.py
version.json

Changelog was already updated in https://github.com/mozilla-releng/scriptworker/pull/572/files#diff-e2de3cbc57ab9b097fca7d7c444c094ba3c1d4ee92b36d972d0d9d49669436cc

scriptworker 45.0.0

---

tests/test_production.py

~~Some indices don't exist yet so let's wait until we ship a few more Android releases before merging this PR.~~ Edit: It turns they already do exist!

Bug 1799696 - Update CoT production tests with new indices

---

src/scriptworker/constants.py

fix: Fix comm-esr115 misspelling

---

HISTORY.rst
src/scriptworker/constants.py
src/scriptworker/version.py
version.json

This will be a permanent project branch that is set-up for the express purpose of testing nightlies and updates.

bug 1845368: add pine to all-nightly-branches

---

src/scriptworker/constants.py

Goes with PR #762 in scriptworker-scripts repo.

Bug 1822689 - Add Thunderbird Flathub scopes.

---

HISTORY.rst
src/scriptworker/constants.py
src/scriptworker/version.py
version.json

~~WIP while new keys are generated.~~ We got the new keys.

Bug 1868558 - Add new CoT keys as part of the Dec 2023 rotation

---

.gitignore
setup.py
taskcluster/kinds/docker-image/kind.yml
taskcluster/kinds/tox/kind.yml
tox.ini

Also adds .test/ folder to .gitignore for running pytest manually

[chore] Remove py37

---

HISTORY.rst
src/scriptworker/constants.py
src/scriptworker/version.py
tests/test_production.py
version.json

Depends on https://github.com/mozilla-releng/scriptworker/pull/629

Bug 1868558 - Distrust old CoT keys

---

HISTORY.rst
src/scriptworker/artifacts.py
src/scriptworker/constants.py
src/scriptworker/cot/verify.py
src/scriptworker/version.py
version.json

Sorry, this is a re-do of #636 !

Bug 1877483 - add larch to all-nightly-branches 

---

src/scriptworker/task.py
tests/test_artifacts.py
tests/test_task.py
tests/test_worker.py

This will be needed to fix https://bugzilla.mozilla.org/show_bug.cgi?id=1967787.

feat: expose RUN_ID and TASKCLUSTER_ROOT_URL to scriptworkers
