mozilla-releng/scriptworker

- CHANGELOG.md
- scriptworker/context.py
- tests/test_context.py
Once upon a time I thought the scripts run in scriptworker would need the temporary credentials and reclaim_task info from TaskCluster.  Neither signingscript nor funsize-balrogworker need them; let's remove that functionality until we have good need for it.
> Remove creds json

- CHANGELOG.md
- config_example.json
- scriptworker/client.py
- scriptworker/config.py
- scriptworker/context.py
- tests/test_client.py
- tests/test_config.py
- tests/test_context.py
- tests/test_integration.py
- tests/test_log.py
- tests/test_poll.py
- tests/test_task.py
- tests/test_utils.py
- tests/test_version.py
- tests/test_worker.py
This function both validates a URL is not pointing off at some untrusted external resource, and returns what we believe is the filepath of the resource.  The filepath can include some relative directory paths, which helps differentiate artifacts that have the same filename, but different filepaths.
> add `validate_artifact_url`

- CHANGELOG.md
- config_example.json
- scriptworker/config.py
- scriptworker/task.py
- scriptworker/utils.py
- scriptworker/version.py
- tests/__init__.py
- tests/test_task.py
- tests/test_utils.py
- version.json
Previously, scriptworker required a flat `artifact_dir`, and used `glob.glob` to find all files, and uploaded them to `public/env/FILENAME`.  I wanted to eventually support subdirectories in `artifact_dir`, but saw no pressing need to add it immediately.
@acmiyaguchi found that the Android builds use the same filename, but different subdirectories.  Because we're using a flat `artifact_dir`, one overwrites the other.
This is the third set of commits to support subdirs.  The previous two dealt with `scriptworker.client.validate_artifact_url`:
* https://github.com/mozilla-releng/scriptworker/pull/7
* https://github.com/mozilla-releng/signingscript/pull/8
This has to do with the artifact uploads.
> Artifact subdirs

- CHANGELOG.md
- scriptworker/poll.py
- scriptworker/version.py
- version.json
I've been assuming that `message_info['task_info']` will always look like
```python
{
"taskId": "...",
"runId": 0
}
```
However, in [this changeset](https://github.com/taskcluster/taskcluster-queue/pull/124/files#diff-2ba94b1f0cbf39f965dbec5a3f38019cR592), @jonasfj added a `hintId`.
This change explicitly passes `taskId` and `runId` rather than using `message_info['task_info']` as kwargs.
After pushing this patch, and a puppet-specific change, to puppet, the signing scriptworkers began claiming new tasks again.
> 0.8.1: explicitly pass taskId and runId from the azure json

- scriptworker/config.py
- scriptworker/test/test_config.py
Like discussed [in this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1306307#c9), taskcluster doesn't allow more than 22 characters for IDs. If an instance is configured with an invalid ID, the failure occurs only when the first task is being handled. As @catlee suggested offline, we can fail earlier, like when the configuration is parsed.
> config: Enforce the 22-character-limit imposed by Taskcluster

- CHANGELOG.md
- scriptworker/gpg.py
- scriptworker/test/test_worker.py
- scriptworker/version.py
- scriptworker/worker.py
- version.json
* The symptoms involved the polling dying, but not the git pull.  Instead of relying on a single `create_task` and then an `loop.run_forever()` to poll, put a `loop.run_until_complete()` inside a `while True` loop.  The git pulls are happening every 5 minutes as desired, and the taskcluster polling is still going.
* Log the traceback if we hit any exceptions running `async_main`.  I noticed that supervisor was restarting the process a lot while github was down on Friday, and I wasn't sure what was breaking.  This should give us more info.
* Remove the `rebuild_gpg_homedirs_loop()` basedir after we're done copying the contents, instead of at the beginning of the call.  This helps avoid having background processes step on each other.  We may end up having to monitor the tmpdir for freshness …
> 0.8.2: fix polling

- CHANGELOG.md
- config_example.json
- scriptworker/constants.py
- scriptworker/gpg.py
- scriptworker/log.py
- scriptworker/test/data/gen1000keys.py
- scriptworker/test/test_gpg.py
- scriptworker/test/test_worker.py
- scriptworker/version.py
- scriptworker/worker.py
- setup.py
- version.json
Per the commit message:
```
Originally, gpg homedir creation happened before scriptworker launched,
and then a background async task polled git and rebuilt the gpg homedirs
if it found a new valid git commit.  In order to sign the gpg keys in
the background, we used async pexpect.
However, as noted in #21, async pexpect isn't reliable currently.  Our
options included fixing the upstream pexpect bug or pulling the gpg
homedir creation into a separate process that we can call via cron.
This patch allows us to use that latter approach.
```
Fixes #21 .
@JohanLorenzo , I'll let you thumb wrestle with @lundjordan with review now that he's back :)  I'm happy to have either of you review.  Thanks to both of you!
I'm going to release scriptworker 0.9.0 off this PR once it's approved.
> 0.9.0: Pull gpg homedir creation out of the main scriptworker process.

- scriptworker/cot/verify.py
- scriptworker/test/test_cot_verify.py
Previously, we had no way of matching up built docker image hashes and the docker image used:
- docker-image build would report the sha of the tarball
- build would report the sha of the docker image built from the tarball
with https://github.com/taskcluster/docker-worker/pull/262 (which is live as of earlier this week), the build also reports the sha of the downloaded image tarball as `imageArtifactHash`, which we can compare to the sha from the docker-image build.  Thanks @gregarndt!
> bug 1315415 - use imageArtifactHash to verify built docker image hashes

- CHANGELOG.md
- docs/chain_of_trust.md
- scriptworker/cot/verify.py
- scriptworker/log.py
- scriptworker/task.py
- scriptworker/test/test_cot_verify.py
- scriptworker/test/test_task.py
We have pointers to the existing artifacts in other tasks, and now the
log is more verbose around what we're doing.  I think we can make the
log more readable, but I think we have a good coverage of information at
least.
Fixes #35.
> stop uploading all the downloaded chain of trust artifacts

- CHANGELOG.md
- scriptworker/test/test_worker.py
- scriptworker/worker.py
In #34 we're hitting an uncaught exception during `upload_artifacts`.
This patch catches it, logs the error, and marks the task as
`resource-unavailable`.
@JohanLorenzo @lundjordan sorry for all the review requests! I'm hoping that a lot of smaller reviews is easier than one big one.
> catch aiohttp exceptions during upload_artifacts.

- scriptworker/constants.py
- scriptworker/cot/verify.py
- scriptworker/test/test_cot_verify.py
@lundjordan @MihaiTabara you will need this PR to land before scriptworker can support beetmover and balrog.  I haven't tested everything all together, but hopefully this Just Works :)
> Support beetmover and balrog in chain of trust verification

- docs/new_instance.md
- scriptworker/constants.py
This PR adds the new docker-image sha, per [bug 1326436](https://bugzilla.mozilla.org/show_bug.cgi?id=1326436).
There's also a ride-along doc update (adding .html to the chain_of_trust link).
@lundjordan @JohanLorenzo if you have a moment :)
> Bug 1326436

- scriptworker/config.py
- scriptworker/test/test_config.py
If you don't specify credentials (either because you forgot, or because you didn't paste things correctly in `secrets.json`), you end up with: `scriptworker.yaml credentials: type <class 'NoneType'> is not <class 'frozendict.frozendict'>!`
This patch replaces with that one instead:
```
scriptworker.yaml credentials needs to be defined!
```
> Enhance error message when creds are missing

- CHANGELOG.md
- scriptworker/poll.py
- scriptworker/test/__init__.py
- scriptworker/test/test_poll.py
While testing the nightly migration on the `date` branch, we noticed
scriptworker was slogging through a lot of tasks that were "already
claimed by another worker".  These turned out to be cancelled tasks, and
they stayed in the Azure queue because we didn't delete them.
This patch deletes those tasks from the Azure queue on status code 409.
It also adds retries and catches in `find_task`, making it more robust.
This is already running on beetmoverworker-1, and we've cleared out a
backlog of cancelled tasks from the queue because of it.
This patch fixes #55.
> Delete cancelled or claimed tasks from azure queue.

- scriptworker/log.py
- scriptworker/task.py
- scriptworker/test/test_log.py
- scriptworker/test/test_task.py
Spin off that came out of [this discussion in #53](https://github.com/mozilla-releng/scriptworker/pull/53#discussion_r95844412). I split the changes in a new PR in order to make the review simpler.
PR also tested manually with https://tools.taskcluster.net/task-inspector/#ZXKOTGt1Qq6rUmPFDKfDmw/0
> Use only one log file (live_backing.log)

- scriptworker/artifacts.py
- scriptworker/cot/verify.py
- scriptworker/task.py
- scriptworker/test/test_artifacts.py
- scriptworker/test/test_task.py
- scriptworker/worker.py
~[WIP: _Tests are on their way_]~
This requires:
1. the presence of a public/logs/live_backing.log
2. the file to be gzip'd
3. and served as a gzip on S3
Edit: Depends on #59
> Make failures report on Treeherder

- scriptworker/constants.py
- scriptworker/cot/verify.py
- scriptworker/test/test_cot_verify.py
@JohanLorenzo This adds initial pushapk support to the chain of trust verification in scriptworker.
Speaking of: we're ready to turn on tier1 taskcluster android nightlies tonight, and that will possibly merge to aurora next week.  If that happens, we would be able to then get pushapk into the nightly graph with chain of trust support, and we could turn off the pushapk scheduler.
If that doesn't happen next week, we're still thinking about getting tc android nightlies turned on in Aurora over the next 6-7 weeks, so it'll happen sooner or later.
> support pushapk in chain of trust

- scriptworker/config.py
- scriptworker/test/__init__.py
- scriptworker/test/test_config.py
- scriptworker/test/test_integration.py
This is a bigger patch than I was expecting, mainly because I didn't
catch some errors in the initial `unfreeze_values` patch.
@johanlorenzo how does this look?  This doesn't block anything, but might be nice to fix before we roll out 2.0.0b1 :)
> start using `unfreeze_values`

- scriptworker/constants.py
It seems like a [renaming happened 2 weeks ago](https://bugzilla.mozilla.org/show_bug.cgi?id=1320328). This causes [issues described here](https://bugzilla.mozilla.org/show_bug.cgi?id=1333394).
@escapewindow , if I'm correct, we're gonna need v1.0.0b8 quickly. I can prepare a v1 branch upon which I can backport this patch.
> Bug 1333394 - Use the new name of docker-images

- scriptworker/constants.py
Also rename the current `release` and `nightly` branch aliases to
`all-release-branches` and `all-nightly-branches`, because they are a
superset of the repos for those releases.  Restricting `release`,
`beta`, and `nightly` to the actual repos used for those release trains
will let us avoid pushing the wrong apk to the wrong product (though the
product name helps avoid that as well).
Finally, avoid using the broken taskcluster 1.0.0 and 1.0.1 packages.
@JohanLorenzo , what do you think?
>  Restrict googleplay scopes.

- scriptworker/constants.py
- scriptworker/test/test_utils.py
- scriptworker/test/test_worker.py
- scriptworker/utils.py
- scriptworker/worker.py
- reduce `aiohttp_max_connections` to 15
- add `intermittent-task` status; use it for aiohttp exceptions in
`scriptworker.worker.run_loop`
- add a `retry_async_kwargs` kwarg to `retry_request`
- add a `scriptworker.utils.calculate_sleep_time` function, because
`taskcluster.utils.calculateSleepTime` generally returns a value less
than 1, and our retries need more flexibility.
- add a `sleeptime_kwargs` kwarg to `retry_async
- add full `scriptworker.utils` test coverage.  We had coverage from
calling other functions that called `scriptworker.utils` functions
already, but now `scriptworker.test.test_utils` fully and directly
tests `scriptworker.utils`.
This also pins `taskcluster<1.0.0` until https://github.com/taskcluster/taskcluster-client.py/issues/58 is fixed.
This should address #20 .
> bug 1333895 - make retries more robust.

- scriptworker/artifacts.py
- scriptworker/test/test_artifacts.py
First, `taskcluster>=1.0.0` changes how we make new artifact urls.  I think this is an improvement, but it breaks `get_artifact_url`.  I added support for 1.0.x without breaking 0.3.x for now; we can tear out 0.3.x support once we're on >=1.0.0 for a while and don't foresee needing to go back.
Second, while debugging async uploads, we see lots of this:
```
2017-01-25 19:29:53,340 - scriptworker.utils - DEBUG - retry_async: <function put at 0x7f99bcc7f2f0>: sleeping before retry
2017-01-25 19:29:53,341 - beetmoverscript.script - INFO - 200
2017-01-25 19:29:53,342 - beetmoverscript.script - INFO - 
2017-01-25 19:29:53,349 - beetmoverscript.script - INFO - 200
2017-01-25 19:29:53,350 - beetmoverscript.script - INFO - 
2017-01-25 19:29:53,355 - beetmoverscript.script - INFO - 200
2017-01-25 …
```
> fix taskcluster>=1.0.0 support; improve upload logging

- .travis.yml
- tox.ini
we probably still need to wait until taskcluster-client.py fully
supports py36 to switch over, but running py36 tests will allow us
to keep py36 scriptworker green in the meantime.
> add python 3.6 support

- scriptworker/cot/verify.py
- scriptworker/test/test_cot_verify.py
Only look for tasks inside the task-graph.json if they are not decision
tasks.  (If we generate decision tasks inside the task graph that can
not themselves be traceable back to the tree standalone, we'll need to
revisit this decision.)
Also, allow for more than 2 decision tasks.
Fixes #77 (references https://bugzilla.mozilla.org/show_bug.cgi?id=1338933 )
> allow for retriggered decision tasks

- scriptworker/constants.py
Since we didn't get to ship any release with current {beetmover,balrog}script workers, I think it's safe to overwrite the release-related ones with the new scopes format. For the nightly scopes, we keep the old scopes and add the new scope format. We're likely to delete the former once testing is done and we're backward compatible and green to go.
> Bug 1338186 - add beetmover/balrog release scopes. r=aki

- MANIFEST.in
- docs/chain_of_trust.md
- helper_scripts/create_gpg_keys.py
- helper_scripts/gpg_helper.sh
This is still a work in progress and shouldn't be merged currently.
Add gpg_helper.sh script which allows running of gpg commands with a specific gpg binary and over a particular gpg homedir, declared either as environment variables or as command line arguments.
The issue with using `getopts` to enable the use of named arguments (`-b` for the binary and `-h` for the home folder) is that it requires to separate the rest of the commands with a double dash (`--`).
This way, for example, invoking the script would look like `./gpg_helper.sh -b /usr/local/bin/gpg2 -h ~/.gnupg -- --list-all`
Another option would be to ditch the use of getopts and just rely on the position of the arguments (the first argument would be the binary, the second the home folder, the rest would be gpg commands), which …
> add helper scripts

- requirements-dev.txt
- scriptworker/artifacts.py
- scriptworker/test/test_worker.py
- scriptworker/worker.py
- setup.py
Addresses #93 .
We may want to look at all of http://aiohttp.readthedocs.io/en/stable/migration.html to make sure we're using aiohttp 2.0.0 properly.
> support aiohttp 2.0.0

- scriptworker/constants.py
- scriptworker/cot/verify.py
- scriptworker/test/test_cot_verify.py
Fixes #91. Unlike the solution suggested there, we use a sorted list of tuples instead of a dict. This simplifies the logic in `build_task_dependencies()`. 
Added new unit test. Also tested manually at https://tools.taskcluster.net/task-inspector/#GZI4I9GmSPW3kK_K_9xBmA/4 (the task failed for another reason that is not due to scriptworker).
r? @escapewindow
> CoT verify: Allow to declare several times the same task type

- scriptworker/artifacts.py
- scriptworker/cot/verify.py
- scriptworker/test/test_artifacts.py
PushAPK needs this list, and beetmover [already implements](https://github.com/mozilla-releng/beetmoverscript/blob/d6d69ef5ee2789569b076f46557f8f9d36b5ffda/beetmoverscript/task.py#L106) the same bits. 
I'm not too sure sorting by taskId is the best data structure. PushAPK doesn't need it, and beetmover sorts by locale.
> Add get_upstream_artifacts()

- scriptworker/constants.py
@JohanLorenzo and I talked about this a bit on IRC and decided we could clean up the other channels, too. I don't think there's any reason we need to have "date" in the scopes for Aurora, since we wouldn't want those builds pushed to the Play Store (the branding is wrong).
> Clean up google play scopes and switch Google Play Aurora to nightly.

- scriptworker/task.py
- scriptworker/test/test_worker.py
We now have nagios monitoring! Which checks `worker.log` age.
Previously, polling was very noisy, so we knew when scriptworker was running and not hung. Now, claimWork is very silent until we claim a task to run. Let's add a debug message, so we know we're running, and nagios doesn't alert.
Also, fix a test warning.
> claimWork logging

- scriptworker/cot/verify.py
- scriptworker/test/test_cot_verify.py
We specify the `taskId` in the chain of trust artifact to help us verify
it matches the task we downloaded it from. We seem to be missing a test
to make sure they match. This patch adds that test.
> verify cot.taskId matches link.task_id

- docs/cot_gpg_key_mgmt.rst
- docs/new_instance.md
We've moved from signed commits to signed tags in cot-gpg-keys. Updating the docs to match.
> signed tag, not signed commit

- scriptworker/log.py
In [bug 1389978](https://bugzilla.mozilla.org/show_bug.cgi?id=1389978), Nick found we were keeping tons of old log filehandles open, which ate up a ton of disk. Let's not do that.
> bug 1389978 - close the contextual log file handle

- CHANGELOG.md
- scriptworker/constants.py
- scriptworker/log.py
- scriptworker/test/test_log.py
- scriptworker/version.py
- version.json
We may be leaving behind open filehandles to the `logrotate.d` files. This should be cleaner.
@kmoir - These are your patches + mine; yours lgtm. Do you feel comfortable reviewing this? I hope I didn't step on your toes when I added a patch - the intent was to help, not take over.
- removes log rotation prefs
- switches `RotatingFileHandler` for `WatchedFileHandler` (prod) or `FileHandler` (scriptworker unit tests). We'll need to set `watch_log_file` to True in [puppet](https://hg.mozilla.org/build/puppet/file/tip/modules/scriptworker/templates/scriptworker.yaml.erb#l31).
- closes test logging filehandles after the tests run, so we don't run into similar problems while running scriptworker unit tests.
> Stop rotating scriptworker logs in scriptworker; add WatchedFileHandler support

- scriptworker/constants.py
Update the defaults, so scriptworker instances set up outside puppet can still verify CoT.
> add decision 0.1.10 + comments

- scriptworker/cot/verify.py
- scriptworker/test/test_cot_verify.py
Currently getting 
scriptworker.exceptions.CoTError: 'Invalid task type for signing:partials!'
This patch should add partials to the valid task types for CoT support.
> Bug 1394242 Support for partials CoT

- scriptworker/constants.py
We want to store key related metadata in json files.
> [docker-worker] Ignore json suffixes. r=aki

- CHANGELOG.md
- scriptworker/cot/verify.py
- scriptworker/version.py
- version.json
These paths recently changed as part of
https://bugzilla.mozilla.org/show_bug.cgi?id=1338651#c195 so CoT needs
to support both while the change rides the trains.
> Bug 1395680: allow /home/worker or /builds/worker

- scriptworker/cot/verify.py
The normal case here is no command -- /home/builds is allowed for legacy
build-image tasks only.
> Bug 1395680 - revert build_image check

- CHANGELOG.md
- scriptworker/cot/verify.py
- scriptworker/test/test_cot_verify.py
The current assumption is decision tasks should be standalone and
verifiable as-is. This is fallout from
https://github.com/mozilla-releng/scriptworker/commit/0356bbb4b8e73c9af4d8a2ca7eec4e88cc0b97a6#diff-340a1f42e56ecb68f523d2badfa58686L513 .
I was able to run `verify_cot` against the failing fennec signing task
and its decision task; they now pass.
> bug 1396517 - don't add a decision task's decision task to cot

- scriptworker/constants.py
- scriptworker/worker.py
After some delays with beetmover executions, there's a way we can save some wall time with sequential scriptworker tasks.
Looking at task graph FvLr0IZYQiWC-OfjF-NT5Q there were between 238 and 252 tasks for each beetmoverworker.  Picking an individual beetmoverworker - number 3, the first task was at 11:40:42 and the final one started at 14:22:25, a total wall time of 2h41m43s. 
The tasks themselves are small, taking a mean of 23s. Looking further there was a mean delay between one task ending and the next beginning, of 12.28s. Not meaningful when there are a few big tasks, but with ~250 per node per release, it adds up to a wall time of roughly 51 minutes.
The main loop in the scriptworker is doing this:
```
if I have a task:
do the task
sleep(1)
sleep(5)
return
```
in the outer …
> Refactor out delays between task executions

- CHANGELOG.md
- README.rst
- scriptworker/cot/verify.py
- scriptworker/task.py
- scriptworker/test/test_cot_verify.py
- scriptworker/version.py
- version.json
Action tasks are now full fledged graph- or subgraph- generators. This task's `task.extra.parent` points at the decision- or action- task that generated this task, so when we verify our task definition, we should look at the parent instead of the decision task. Action tasks should still check their decision task's validity; in the future we'll rebuild their task definitions from their context and the decision task's `actions.json`.
This should fix our retrigger verifications once [bug 1370343](https://bugzilla.mozilla.org/show_bug.cgi?id=1370343)  is fixed.
> bug 1393277 - cot-verifiable action/parent tasks.

- CHANGELOG.md
- scriptworker/cot/verify.py
- scriptworker/test/test_cot_verify.py
@MihaiTabara this is another one you can look at :) No rush on any of these.
`verify_cot` breaks when run against a docker-worker task, because we
try to verify chain.cot for docker-worker specific info. Because the
chain object is assumed to be the currently running task, we don't
create a cot object for it.
I ran into this while testing
```
verify_cot --task-type l10n --cleanup -- Tz_iPxtTRqCLBg64rHK8uQ
```
> don't run docker-worker tests on the chain object

- CHANGELOG.md
- scriptworker/version.py
- version.json
I just landed #169. I see #170 is ready too (but not #171). I don't mind if 6.0.0 includes #170. However, the changes there don't require a major version bump, so we can easily release 6.1.0 right after. @escapewindow, @tomprince, what do you guys think?
> Bump 6.0.0

- CHANGELOG.md
- scriptworker/constants.py
- scriptworker/cot/verify.py
- scriptworker/test/test_cot_verify.py
- scriptworker/version.py
- version.json
Way back in the day, I decided no chain of trust should need to be longer than 5 tasks in length; any longer and it was a sign of a DOS attack or misconfiguration.
In https://bugzilla.mozilla.org/show_bug.cgi?id=1431110 we're seeing new valid tasks that have chains of 7? in length.
This patch makes the `max_chain_length` configurable, and sets it to a default of 20 for now.
With this patch, `verify_cot --task-type balrog --cleanup -- HDb0RySlTluYbmzopHjg-w` works. Without it, it breaks on `Too deep recursion`.
> bug 1431110 - allow for default `max_chain_length` of 20.

- requirements-dev.txt
- setup.py
aiohttp 3.0.0 was [released yesterday](https://github.com/aio-libs/aiohttp/releases/tag/v3.0.0). Scriptworker has an installation problem, because taskcluster [prevents 3.0.0 from being installed](https://github.com/taskcluster/taskcluster-client.py/pull/67).
Even if we wanted taskcluster to allow 3.0.0, we would hit this [new type of failure](https://travis-ci.org/mozilla-releng/beetmoverscript/jobs/340871448#L599).
Therefore, let's first ride the 2.x.y versions and see how we can bump it on taskcluster and *script.
> Freeze aiohttp to 2.x.y

- scriptworker/test/test_integration.py
- scriptworker/test/test_worker.py
- scriptworker/worker.py
If a scriptworker gets the SIGTERM signal, it will wait for the current task (if any) to finish, and then exit.
This should allow supervisor to safely restart scriptworkers, as long as tasks can be resolved in a short time.
> Implement graceful shutdown on SIGTERM

- CHANGELOG.md
- scriptworker.yaml.tmpl
- scriptworker/artifacts.py
- scriptworker/constants.py
- scriptworker/test/test_artifacts.py
- scriptworker/test/test_context.py
- scriptworker/test/test_integration.py
- scriptworker/test/test_task.py
This is what we do in-tree for docker-worker (and I think generic-worker) tasks; let's do the same in scriptworker.
> set artifact expiration date to task expiration date

- docs/new_instance.md
- helper_scripts/create_gpg_keys.py
Got tired of renaming all the hostnames to fqdns.
We want user@fqdn.pub in cot-gpg-keys; on releng-puppet2 we want just fqdn. I compromised by naming the pub file user@fqdn.pub, and the sec file fqdn.sec.
Non-urgent.
> new gpg key fixes

- docs/releases.md
This gets rid of uploading gpg signatures to pypi as well (see [here](https://caremad.io/posts/2013/07/packaging-signing-not-holy-grail/) for reasoning).
> Distribute wheels of scriptworker.

- scriptworker/cot/verify.py
We were logging `verify_chain_of_trust` with
`scriptworker.cot.verify.log`, which is set to
`logging.getLogger(__name__)`. This meant that any scriptworker
functions outside of the scriptworker.cot.verify namespace weren't being
logged.
Now we're logging `verify_chain_of_trust` with a `scriptworker`
namespace.
Fixes #175.
> log all scriptworker events in `verify_chain_of_trust`

- CHANGELOG.md
- scriptworker/cot/verify.py
- scriptworker/version.py
- version.json
Evidently `./mach try` now appends a "Pushed via `mach try syntax`" line to the try commit message. The net result is that the task's GECKO_COMMIT_MSG only matches the first line of the push's commit message.
Without this change, `verify_cot --cleanup --task-type decision UTeFpv0GRZ-Z0P5Fv1oBeg` falls back to cotv1. With this change, it verifies cleanly in cotv2.
> allow for try syntax in comment (only first line)

- CHANGELOG.md
- scriptworker/cot/verify.py
- scriptworker/test/test_cot_verify.py
- scriptworker/version.py
- version.json
We don't just use the first line of a comment in a try push; we trim everything before `try:`.
Without this change, `verify_cot --task-type decision --cleanup IfGymcgYRnCwGP3uR9wA9w` fails cotv2 and fails back to cotv1. With this change, `verify_cot --task-type decision --cleanup IfGymcgYRnCwGP3uR9wA9w` works.
> Fix try comments part 2

- scriptworker/client.py
- scriptworker/test/__init__.py
- scriptworker/test/test_client.py
- scriptworker/test/test_cot_verify.py
attempt to fix #225. This was fine when we were running tests synchronously, but mocking `get_event_loop` when we're running a number of tests concurrently seems potentially dangerous.
> address event loop bustage in concurrent tests

- scriptworker/test/__init__.py
- scriptworker/test/test_artifacts.py
- scriptworker/test/test_client.py
- scriptworker/test/test_cot_verify.py
- scriptworker/test/test_gpg.py
- scriptworker/test/test_log.py
- scriptworker/test/test_task.py
- scriptworker/test/test_utils.py
- scriptworker/test/test_worker.py
Scriptworker tests have been flaky of late, using both pytest-asyncio and pytest-xdist with 4 parallel tests; the symptom is a bunch of tests failed with closed event loop errors. Removing the `event_loop` fixture appears to address this flakiness. I believe some \*scripts import the `event_loop` fixture; we should be able to apply similar fixes downstream. (If we don't, then the imports will fail when we release a new scriptworker with these patches. I can do a pass through the various \*scripts.)
Also, our tests have been peppered with aiohttp unclosed session warnings. I tracked these down to the `rw_context` fixture; by adding an explicit close for `context.session`, `context.queue.session`, and `context.temp_queue.session` if they exist and are `aiohttp.ClientSession` instances, we …
> Fix intermittent test bustage + unclosed session warnings

- scriptworker/context.py
- scriptworker/gpg.py
- scriptworker/test/__init__.py
- scriptworker/test/test_context.py
- scriptworker/test/test_gpg.py
- scriptworker/test/test_worker.py
- scriptworker/worker.py
Create a `context.event_loop` property to standardize the loop we use.
In regular usage, we default to `asyncio.get_event_loop()`. In testing,
we're using `pytest-asyncio` which creates new `event_loop` fixtures per
test and closes them at the end; and `pytest-xdist` which runs tests in
parallel. When combined, bare `asyncio.get_event_loop()` calls can
result in intermittent bustage (closed loop errors).
By modifying the `rw_context` fixture to populate its `event_loop` with
the `pytest-asyncio` `event_loop`, we get most of the way to the fix.
`main` and `rebuild_gpg_homedirs` are entry points that create their own
`context` objects, so they now take optional `event_loop` kwargs to
override the loop during testing.
> explicitly pass in an `event_loop` in testing.

- CHANGELOG.md
- scriptworker/cot/verify.py
- scriptworker/test/test_cot_verify.py
- scriptworker/version.py
In [bug 1486532](https://bugzil.la/1486532) empty properties in generic-worker task payloads in gecko decision task generated tasks will be disappearing. Currently, scriptworker guesses worker implementation based on properties that are included in the task payloads. Therefore, if these properties disappear, this guessing function will unfortunately no longer work. However, the good news is, there is trustworthy metadata contained in the gecko decision-task generated task definitions which provides this information, which is the `worker-implementation` tag. I suspect this didn't exist when the worker implementation guess code was written, but now that it does, it should be a reliable source of information.
I'm not sure if scriptworker evaluates tasks that are generated outside of the …
> Bug 1486532 - consider task['tags']['worker-implementation'] when guessing worker implementation

- CHANGELOG.md
- scriptworker/constants.py
- scriptworker/version.py
- version.json
Once https://github.com/mozilla-releng/build-puppet/pull/165 has landed,
the staging bouncerworker no longer has access to production credentials,
so it is safe to allow level 1 trees to run jobs on it.
> Bug 1483326: Don't restrict access to the -dev bouncerwork.

- CHANGELOG.md
- scriptworker/constants.py
- scriptworker/cot/verify.py
- scriptworker/task.py
- scriptworker/test/test_cot_verify.py
- scriptworker/test/test_task.py
- scriptworker/version.py
- version.json
I tested `verify_cot` against a signing task scheduled by:
* a cron task  https://tools.taskcluster.net/groups/fj-ZwGVcT3-eBCTJElE0KQ/tasks/TosAq2dRRI2yxw221ECStQ/details
* and a release one https://tools.taskcluster.net/groups/RfhACY0wTCGdSNu7dLwpnw/tasks/YY2vQg2YSMq97NWsGDJIhw/details
with the following command:
``` sh
verify_cot --task-type signing --cleanup --cot-product mobile -- ${signingTaskId}
```
I didn't run the script against real worker, so I made these adjustments locally: https://gist.github.com/JohanLorenzo/06d11681c400f202dc37baf584a707d6
Both scenario ran fine against the current diff. You can see what `.taskcluster.yml` looks like here: https://github.com/mozilla-mobile/focus-android/compare/master...JohanLorenzo:full-chain-of-trust
I made the choice of not defining new …
> Bug 1486089 - Support "github-release" tasks_for and cron of mobile

- scriptworker/cot/verify.py
- scriptworker/test/__init__.py
- tox.ini
This is a test-focused PR, driven by the latest aiohttp deprecation warnings.
- move the bulk of the `verify_cot_cmdln` logic into an async function, which allows us to use `await` and `async with` rather than keep on calling `event_loop.run_until_complete`.
- modify `rw_context` and `mobile_rw_context` to use `async with aiohttp.ClientSession() as session:` to get rid of the rest of the aiohttp deprecation warnings.
- fix pytest-random-order with `--random-order`.
- add a slowest 10 tests measurement, with `--durations=10`.
Fixes #295.
> Aiohttp warnings

- scriptworker/artifacts.py
- scriptworker/cot/verify.py
- scriptworker/exceptions.py
- scriptworker/test/__init__.py
- scriptworker/test/test_utils.py
- scriptworker/utils.py
I noticed that we were retrying 404s for downloading the currently largely nonexistent `chain-of-trust.json{,.sig}` files in #294... this means it takes us a few minutes to realize that yes, the file is in fact missing. I *think* not retrying on 404 is ok; if the file is there but we have other issues, it'll be a non-404 status.
If we think this might have larger repercussions, I can retry on `BaseDownloadError` in most cases, and override that with just `DownloadError` specifically for downloading `chain-of-trust.json{,.sig}` until we create those files across all 3 worker implementations.
What do you think, @JohanLorenzo , @tomprince ?
> Don't retry on 404s.

- scriptworker.yaml.tmpl
- scriptworker/constants.py
- scriptworker/gpg.py
- scriptworker/test/test_gpg.py
- scriptworker/version.py
- version.json
This is very similar to `gpg_path`. We will need this because the `git` binary is not in PATH in the nix generated docker images.
> Use `git_path` for git binary

- CHANGELOG.md
- scriptworker.yaml.tmpl
- scriptworker/constants.py
- scriptworker/cot/verify.py
- scriptworker/github.py
- scriptworker/task.py
- scriptworker/test/test_cot_verify.py
- scriptworker/test/test_github.py
- scriptworker/test/test_task.py
- scriptworker/test/test_utils.py
- scriptworker/utils.py
- setup.py
- version.json
Blocks https://github.com/mozilla-mobile/android-components/pull/1874
> Allow mobile to create in-tree docker images

- CHANGELOG.md
- scriptworker/constants.py
- scriptworker/cot/verify.py
- scriptworker/github.py
- scriptworker/task.py
- scriptworker/test/test_cot_verify.py
- scriptworker/test/test_github.py
- scriptworker/test/test_task.py
- scriptworker/test/test_utils.py
- scriptworker/utils.py
- version.json
And add more checks to detect PRs
> Bug 1529990 - Fix Mobile bustage

- CHANGELOG.md
- scriptworker/cot/verify.py
- scriptworker/test/test_cot_verify.py
- version.json
See https://github.com/mozilla-mobile/reference-browser/pull/716#discussion_r274446504
> Fix #326 - github-push: use committer data instead of author

- CHANGELOG.md
- scriptworker/cot/verify.py
- scriptworker/test/test_cot_verify.py
- version.json
After 0.51.0 was out, I landed https://github.com/mozilla-mobile/android-components/pull/2885 to prevent github releases to be triggered after editing the description or drafting it and instead, only trigger if `Publish` button was pressed. 
0.52.0 was out today and all the tasks failed CoT because `2019-05-13T15:22:38 CRITICAL - beetmover:parent Rq7PmV9jSg-DvRaact5t1w: the runtime task doesn't match any rebuilt definition!`
In order to check CoT, we rebuilt the decision task's definitions from scratch, but because the jsone context misses the `'action':'published'`, it doesn't actually render anything whilst doing the mergedeep in the `.taskcluster.yml`, resulting in an empty `rebuilt_definitions`.
```
(Pdb) pp rebuilt_definitions
{'policy': {'pullRequests': 'public'}, 'tasks': [], …
```
> Bug 1547928 - enrich github releases jsone context with event action

- scriptworker/task.py
- scriptworker/worker.py
- version.json
In GCP we use slugid to generate workerId and it's harder to connect the random k8s replica name to this workerId.
> Log workerId

- CHANGELOG.md
- scriptworker/test/test_worker.py
- scriptworker/worker.py
- version.json
I hit some issues deploying autoscaling in GCP (Kubernetes). The idea was to employ the fact that [Kubernetes sends](https://kubernetes.io/docs/concepts/workloads/pods/pod/?source=post_page---------------------------#termination-of-pods) `SIGTERM` N seconds (30 by default) before killing the container to let the application clean up the state. For some reason I thought that scriptworker handles `SIGTERM`by not taking any more tasks. Apparently we also cancel the running task in order to report `machine-shutdown` and upload logs.
This patch adds another handler for `SIGUSR1` that does almost the same, but without cancelling the running task. We will use the Kubernetes' `preStop` hook to run a script which will send `SIGUSR1` to scriptworker and then watch the status  of the process. If the …
> Graceful shutdown without cancelling via SIGUSR1

- CHANGELOG.md
- requirements/base.in
- scriptworker.yaml.tmpl
- scriptworker/cot/verify.py
- scriptworker/test/__init__.py
- scriptworker/test/test_cot_verify.py
- setup.py
- version.json
The new treescript workers use `cot_job_type` set to `tree` instead of
generic `scriptworker` we use in puppet. This require a new entry in
`get_valid_task_types`.
> Use `verify_scriptworker_task` explicitly

- scriptworker/cot/verify.py
Tracking \*script version logging in https://github.com/mozilla-releng/scriptworker-scripts/issues/17 .
> log scriptworker version near the top of the cot log

- scriptworker/task.py
Fixes https://github.com/mozilla-releng/signingscript/issues/128 .
Note: We may want to allow scripts to exit one of the known status
codes. If so, we should amend this to check if the exit code is in
scriptworker.constants.STATUSES.values(), and return 1 if it's not.
> run_task returns 1 on non-zero exit code, 0 on success.

- CHANGELOG.md
- scriptworker/cot/verify.py
- scriptworker/test/test_cot_verify.py
- scriptworker/version.py
- version.json
Fixes https://taskcluster-artifacts.net/ILSInA2nRFyOd3zOGI8tOg/0/public/logs/chain_of_trust.log: 
```
scriptworker.exceptions.CoTError: CoTError('JSON-e error while rebuilding signing:parent task definition: TemplateError at template.tasks[0]: pusher not found in {"repository": {"full_name": "mozilla-mobile/reference-browser", "html_url": "https://github.com/mozilla-mobile/reference-browser", "pushed_at": null}, "ref": "refs/heads/master", "after": "1875923349a126b224a7e5970ed096723cb37e94", "sender": {"login": "pocmo"}}',)
```
It was introduced in https://github.com/mozilla-mobile/reference-browser/pull/737/files#diff-ac0229d1171c0983b27003af4c7441a5R19. 
cc @pocmo
> Github push: Expose repo name and pusher's email

- scriptworker/client.py
To avoid logging like https://taskcluster-artifacts.net/RReanjm1TiKXVmIkEfFRAQ/0/public/logs/live_backing.log
> reduce mohawk logging to logging.INFO

- CHANGELOG.md
- scriptworker/cot/verify.py
- scriptworker/version.py
- version.json
Regressed in #368. @ColinTheShots came across that error[1]: 
```
scriptworker.exceptions.CoTError: CoTError('Error while rebuilding signing:parent M-3BfvqQQsKov7kas24NoQ task definition!\nUnknown repo for source url https://github.com/colintheshots/fenix!',)
```
@mitchhentges told me he got the same one recently too.
@tomprince said staging releases shouldn't look up known projects anymore[2]. I realized `cron` contexts was still fetching that. This patch fixes this.
It was tested with:
```
verify_cot --cleanup --task-type signing --cot-product mobile 'f3EN1BJUTtWIEj8jurxXFA'
```
[1] https://tools.taskcluster.net/groups/M-3BfvqQQsKov7kas24NoQ/tasks/f3EN1BJUTtWIEj8jurxXFA/runs/0/logs/public%2Flogs%2Fchain_of_trust.log#L126
[2] https://github.com/mozilla-releng/scriptworker/pull/368#pullreq …
> Mobile: Fix staging crons

- scriptworker/constants.py
All three channels of `nightly`, `beta` and `production` should only be sign-able on level 3.
Also note that `release-signing` scope was replaced by `production-signing`, as visible by [this task](https://tools.taskcluster.net/groups/LiA4OwpkTJymka1zFZVc_g/tasks/K0-GhxY4T2WWTCzAG_n_Og/details)
> Update fenix CoT restrictions, adds all release channels

- src/scriptworker/constants.py
This adds a new/separate Chain of Trust public key that will be used for workers in GCP
> add new docker-worker-gcp CoT public key

- HISTORY.rst
- src/scriptworker/artifacts.py
- src/scriptworker/context.py
- src/scriptworker/version.py
- tests/test_artifacts.py
- tests/test_context.py
- tests/test_integration.py
- tox.ini
- version.json
> Temp queue download

- HISTORY.rst
- src/scriptworker/artifacts.py
- src/scriptworker/context.py
- src/scriptworker/version.py
- tests/test_artifacts.py
- tests/test_context.py
- tests/test_integration.py
- version.json
This backs out #434 , which is breaking partner/eme tasks because they don't have the right `get-artifact` scopes.
> revert temp_queue changes until partner/eme tasks have the right scopes

- HISTORY.rst
- README.rst
- src/scriptworker/constants.py
- src/scriptworker/version.py
- tests/test_integration.py
- version.json
This patch adds the scriptworker-scripts cot-product, and cleans up some old configs.
- there is no more aws-provisioner-v1 in https://firefox-ci-tc.services.mozilla.com/provisioners/ , so I removed all workers with that provisioner
- I populated the adhoc-3 workers, though they don't exist yet. Optional.
- I added scriptworker-scripts as a cot product. I wasn't sure which scopes would be restricted, and I'm open about the names.
- birch and jamun appear to be idle for the past year. esr60 is EOL. We don't appear to reference `all-staging-branches` anywhere.
I can split this up if preferred.
> scriptworker cot_product + cleanup

- HISTORY.rst
- src/scriptworker/constants.py
- src/scriptworker/version.py
- version.json
This reverts https://github.com/mozilla-releng/scriptworker/pull/447. It broke mobile releases:
```
2020-04-01T09:34:52    DEBUG -     Verifying the scriptworker:build:docker-image aP4nedQnTAWQl2fKawVGwg docker-worker ed25519 chain of trust signature
2020-04-01T09:34:52 CRITICAL - Chain of Trust verification error!
Traceback (most recent call last):
File "/app/lib/python3.8/site-packages/scriptworker/cot/verify.py", line 1905, in verify_chain_of_trust
verify_cot_signatures(chain)
File "/app/lib/python3.8/site-packages/scriptworker/cot/verify.py", line 836, in verify_cot_signatures
verify_link_ed25519_cot_signature(chain, link, unsigned_path, ed25519_signature_path)
File "/app/lib/python3.8/site-packages/scriptworker/cot/verify.py", line 815, in verify_link_ed25519_cot_signature
raise …
```
> Bug 1613800 - part 2: add old docker-worker cot key back

- HISTORY.rst
- src/scriptworker/cot/verify.py
- src/scriptworker/task.py
- src/scriptworker/version.py
- tests/test_cot_verify.py
- tests/test_task.py
- version.json
This also detects if the task definition we receive is an empty `{}` (currently just by checking the existence of `payload`). In theory that should be a taskcluster error.
> Bug 1618731 - retry getting task definition

- HISTORY.rst
- src/scriptworker/cot/verify.py
- src/scriptworker/version.py
- tests/test_cot_verify.py
- version.json
The generic-worker rdp info is [here](https://github.com/taskcluster/taskcluster/blob/05c5897fafc9d96f5c7f8f8e9dd0ecb08831c358/workers/generic-worker/schemas/multiuser_windows.yml#L296-L325).
This patch:
1. changes `verify_docker_worker_task` to run `check_interactive_docker_worker`, even if the target task is the `chain` task (i.e., the specific task we want to verify the chain against). Since `check_interactive_docker_worker` doesn't check `link.cot`, we don't require that task to have finished yet.
2. raises `CoTError` on an interactive docker-worker task. Previously we returned a list of errors, which we then ignored. I'm not thrilled with this, but we're partially protected by ci-admin checks and the fact that the interactive flag would need to be set in-tree to affect a release …
> check generic-worker interactive tasks. raise on docker-worker interactive tasks.

- HISTORY.rst
- src/scriptworker/constants.py
- src/scriptworker/cot/verify.py
- src/scriptworker/version.py
- tests/test_cot_verify.py
- version.json
In [this adhoc task](https://firefox-ci-tc.services.mozilla.com/tasks/HNPN1sluQ8mTmLNaG3KB0w), we got a bad `tasks_for` error, because we have a large `if` statement that whitelists a bunch of `cot_product`s.
Let's create a `cot_product_type` map that we can check, so we don't have to update this `if` block every time we add a new github product.
> bug 1594621 - add cot_product_type map

- HISTORY.rst
- src/scriptworker/cot/verify.py
- src/scriptworker/version.py
- tests/test_production.py
- version.json
Previously, we assumed that we would list any and all private github repos in `constants.py`. However, with the xpi project, we'll get many private repos that we will want to verify without needing to land a change in scriptworker.
Let's allow for `ssh://github.com` source urls to imply a private repository.
As ridealongs, I added `--verbose` and `--no-check-task` to `verify-cot`. I also cleaned up some extraneous output at the end of `verify_cot`.
Also, the second patch gets us to stop creating `...` directories while running `test_production.py` tests.
The `base_*_dir` and `task_log_dir_template` config entries were from a historic, unmerged PR. Let's set the actual config paths inside our tempdir. Bonus: we won't have weird bustage related to hardcoded directory paths if and when we …
> fix xpi private cot verification

- tests/test_cot_verify.py
This was taking ~180 seconds plus. Now it takes <1s.
> fix slow test_build_task_dependencies

- HISTORY.rst
- src/scriptworker/cot/verify.py
- src/scriptworker/version.py
- version.json
Fixes #477 .
We can either land and roll this out to support poorly-formed git commits, or we can require people have their git logins properly configured to pass CoT. I don't have strong opinions here, other than the former may save human debugging time.
> allow for unknown `committer_login`.

- HISTORY.rst
- src/scriptworker/cot/verify.py
- src/scriptworker/version.py
- version.json
Should address https://github.com/taskcluster/taskcluster/pull/4277 .
Once taskQueueId is everywhere on all tasks that we want to verify, we can remove it from the ignore list.
> add taskQueueId to the ignore list

- HISTORY.rst
- src/scriptworker/cot/verify.py
- src/scriptworker/version.py
- tox.ini
- version.json
Per #482.
Also address [isort >=5](https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/).
> Add `projectId` to ignore keys

- HISTORY.rst
- src/scriptworker/constants.py
- src/scriptworker/version.py
- version.json
The docker-worker keypair isn't 100% guaranteed to stay the same, but let's roll this out in case it is. At least we'll mark the scriptworker+generic-worker keys valid.
> [RELENG-42] add new scriptworker, docker-worker, and generic-worker cot keys

- HISTORY.rst
- src/scriptworker/constants.py
- src/scriptworker/task.py
- src/scriptworker/version.py
- tests/test_task.py
- version.json
To go with https://github.com/mozilla-releng/scriptworker-scripts/pull/324 .
> 245 and 241 intermittent-task

- HISTORY.rst
- requirements.txt
- src/scriptworker/context.py
- src/scriptworker/utils.py
- src/scriptworker/version.py
- tests/test_client.py
- tests/test_production.py
- tests/test_task.py
- tests/test_worker.py
- version.json
https://github.com/mozilla-releng/scriptworker-scripts/pull/337/files will break on deploy unless we also fix scriptworker's timestamp usage.
> arrow timestamp -> int_timestamp

- HISTORY.rst
- src/scriptworker/constants.py
- src/scriptworker/version.py
- version.json
We never used the previous-new docker-worker CoT key. We're rolling out a new docker-worker CoT key; let's allowlist the pubkey.
> Docker worker cot

- tox.ini
https://github.com/pytest-dev/pytest-asyncio/issues/209 didn't end up fixing the issue, so let's pin `pytest-asyncio<0.15.0`
> pytest asyncio 0.15.1 is broken too

- src/scriptworker/cot/verify.py
- src/scriptworker/utils.py
Taskcluster v41 includes these properties in task definitions.  When
comparing tasks, this normalizes the tasks to always contain `projectId`
and `taskQueueId` and ever `providerId` or `workerType`, following the
same defaults for those properties as Taskcluster itself.
I tested this against the current deployment by emulating the result of `queue.task` when run against v41.  This initially caused task-comparison failures, but with this patch in place `verify_cot` ended with
```
INFO:scriptworker.cot.verify:Good.
```
```diff
diff --git a/src/scriptworker/task.py b/src/scriptworker/task.py
index 1ce9d8c..231b029 100644
--- a/src/scriptworker/task.py
+++ b/src/scriptworker/task.py
@@ -64,16 +64,18 @@ async def get_task_definition(queue, task_id, exception=TaskclusterFailure):
task_id (str): …
```
> Be resilient to the presence of taskQueueId, projectId

- HISTORY.rst
- requirements.txt
- src/scriptworker/version.py
- tests/test_production.py
- version.json
Once we roll this out, this should unblock the firefoxci taskcluster 41.x upgrade.
> Scriptworker 38.0.0

- docs/releases.md
We no longer use puppetagain; update docs for the new rollout procedures.
> update release docs

- .taskcluster.yml
- HISTORY.rst
- requirements.txt
- setup.py
- src/scriptworker/constants.py
- src/scriptworker/version.py
- tests/test_production.py
- tox.ini
- version.json
~The prod tests will show us when the latest release/nightly graphs are all based on tasks using the new keys; let's not merge until these are green, or we explicitly determine that we don't need to wait on a given bustage.~
Green! I had to adjust our test configs to get this green due to #509, but this now fixes #509 as well.
> remove old cot keys

- requirements.txt
- src/scriptworker/config.py
- src/scriptworker/task.py
The API for `claimWork` changed in Taskcluster 40.
This PR greens up the integration tests when we use taskcluster 44.1.0.
As a followup, we should create a long-lived test client like https://firefox-ci-tc.services.mozilla.com/auth/clients/mozilla-auth0%2Fad|Mozilla-LDAP|asasaki%2Fworker-test , put it in TC secrets, and use that to run integration tests in this repo.
> Fix claimWork in scriptworker + tc>39

- src/scriptworker/constants.py
- tests/conftest.py
- tests/data/cotv4/decision_github_private.json
- tests/data/cotv4/private_github_.taskcluster.yml
- tests/test_cot_verify.py
- tests/test_github.py
AFAICT there's no reason to continue supporting the `mpd001` trust domain.
> Replace mpd001 trust domain with mozillavpn

- src/scriptworker/constants.py
Follow-up on a review comment from the pushmsixscript PR.
These scopes match those in pushmsixscript. Now that I see them in this list, I wonder, should they contain ":firefox"?
> Add scope constants for microsoftstore / pushmsixscript.

- src/scriptworker/constants.py
From [Mana - Chain of Trust key rotation](https://mana.mozilla.org/wiki/display/RelEng/Chain+of+Trust+key+rotation?flashId=459232040)
- [RELENG-827 - generate a new generic-worker CoT key](https://mozilla-hub.atlassian.net/browse/RELENG-827)
- [RELOPS-123 - Update gecko-3-b-win2012 images with new CoT key](
https://mozilla-hub.atlassian.net/browse/RELOPS-123)
- [RELENG-830 - mark the new keys as trusted](https://mozilla-hub.atlassian.net/browse/RELENG-830)
Aiui Relops will roll this key out to all generic-worker pools.
> RELENG-830 - add the 2022 generic-worker trusted CoT public key

- tests/test_production.py
I'm guessing the old one hasn't been released in over a year.
I went to shipit to find recent xpi releases and chose the most recent.
Adhoc I looked at the index list and chose something 1 month old I think.
We could potentially mitigate this in the future by adding a generic "latest-release-signing-task-of-any-variety" index to both xpi and adhoc, and pointing at that.
> fix cot test

- src/scriptworker/constants.py
This patch allows autoland branch to push to trees
> Allow autoland branch to use treescript push

- src/scriptworker/constants.py
The scope is used by the "bouncer-locations" on comm-central to
keep the Thunderbird Daily bouncer products pointing to the
latest version.
> Bug 1786838 - Allow comm-central to use production bouncer scope.

- src/scriptworker/constants.py
This is for the Mozilla VPN release promotion action
https://firefox-ci-tc.services.mozilla.com/tasks/EhSwy_MJSfakY0skY8bnUg/runs/0/logs/public/logs/chain_of_trust.log
> Allow tasks for action in Mozilla VPN

- HISTORY.rst
- src/scriptworker/constants.py
Context: @escapewindow reminded me of this type of change in https://github.com/mozilla-releng/scriptworker-scripts/pull/565#discussion_r974524753
> Bug 1786780 - Restrict A-C scopes to both A-C and firefox-android repos

- HISTORY.rst
- src/scriptworker/constants.py
- tests/test_github.py
Just like https://github.com/mozilla-releng/scriptworker-scripts/pull/591, `git grep android-components` gave me all the places I needed to change.
> Bug 1791397 - Remove all references to android-components

- src/scriptworker/constants.py
- tests/test_production.py
There haven't been any xpi-manifest releases recently, so that test is still failing and I marked it as xfail. Once there has been a release, we can change the index to point at it and remove the xfail marker.
> [RELENG-837] - Remove 2021 CoT keys

- HISTORY.rst
- src/scriptworker/version.py
- version.json
This only contains the removal of the 2021 CoT public key.
> Bump scriptworker to version 46.0.0

- src/scriptworker/log.py
- src/scriptworker/utils.py
I have no idea why this started failing, it doesn't appear to be caused by any change in the code.. but at least the fix is simple.
> Fix unused imports for flake8 check

- tests/test_production.py
Ideally we'd look at a build or signing task instead, but those aren't indexed currently so use the docker-image task for now instead.
> Bug 1808492 - add app-services index to production CoT test

- tests/test_production.py
We've rotated the scriptworker CoT key but haven't re-signed everything since.  A lot of these will be fixed next week with the next beta build.
> tests: mark adhoc-signing CoT checks as expected failure, and update fenix index paths

- tests/test_production.py
Today's 1.3.2 release means this test should now pass.
> Mark firefox-translations CoT test as passing

- src/scriptworker/constants.py
pine and oak no longer need nightly-signing, and the mozilla-inbound and fx-team integration repos are defunct.
> Bug 1824931 - clean up old hg branches permissions in chain-of-trust verification

- .readthedocs.yml
- MANIFEST.in
- readthedocs.yml
For https://blog.readthedocs.com/migrate-configuration-v2/
> update .readthedocs.yml to v2

- docs/conf.py
- requirements-docs.txt
From https://readthedocs.org/projects/scriptworker/builds/21236529/, I'm hoping to resolve these issues:
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
WARNING: autodoc: failed to import module 'artifacts' from module 'scriptworker'; the following exception was raised:
No module named 'scriptworker'
jinja2.exceptions.UndefinedError: 'style' is undefined
Works well for me locally.
> try to fix readthedocs builds, again

- src/scriptworker/task.py
- tests/__init__.py
- tests/data/killed.py
- tests/test_worker.py
`run_task`, and thus `do_run_task`, were using the (negative) exit code from the task process as status.  That status was then combined with the 0 from `do_upload` in `RunTasks.invoke` via `worst_level`, and ended up getting swallowed.  Replace that with a failure code.
> Bug 1864413: don't report success for tasks killed by a signal

- src/scriptworker/constants.py
Fixes a regression from PR #624.
This is a temporary situation while Thunderbird monthly releases are in development. Until comm-esr115 is migrated to use a (new) "esr" update channel, it needs to use the "release" channel.
Details why comm-esr115 was able to use "release" prior to now are in the bug.
> Bug 1869123 - Allow comm-esr115 to use the "balrog:server:release" restricted scope.

- pyproject.toml
- tests/__init__.py
- tests/conftest.py
- tests/test_artifacts.py
- tests/test_cot_generate.py
- tests/test_cot_verify.py
- tests/test_github.py
- tests/test_production.py
- tests/test_task.py
- tests/test_worker.py
- tox.ini
Closes #532
The event loop closed issue seems to stem from `aiomemoizettl.py:6` where it uses the event loop to invalidate the cache. Once the invalidation happens, the event loop is already closed, raising an exception.
> unpin pytest-asyncio

- taskcluster/docker/python/Dockerfile
Depends on https://github.com/taskcluster/taskgraph/pull/453
> ci: Use python-slim image for python testing

- src/scriptworker/cot/verify.py
- src/scriptworker/task.py
- tests/test_cot_verify.py
At the moment scriptworker assumes that the sha of the current tip of the PR is correct for all tasks upstream of anything being verified. This is incorrect if a task being verified depends on a cached task (whether from an earlier version of the same PR, or another one altogether).
> fix: ensure pull request head sha is set correctly (fixes #652)

- src/scriptworker/artifacts.py
- src/scriptworker/context.py
- src/scriptworker/cot/verify.py
- tests/test_artifacts.py
- tests/test_context.py
- tests/test_cot_verify.py
This patch allows the deferral of upstream artifact selection to runtime by supporting `*` in upstreamArtifacts `paths`.
This is primarily built to support the work being done to add beetmover support for translations in https://github.com/mozilla/firefox-translations-training/issues/466, but there's no reason it wouldn't work more generally. I've tested it a bunch in that context, and the scriptworke parts (download artifacts and verifying CoT) are working well with this patch. See https://firefox-ci-tc.services.mozilla.com/tasks/YThKSz44QQGIF-b_L3958Q/runs/0 and other beetmover tasks in that graph for examples. (Note that while some of the tasks are failing, all of CoT stuff works - which is the part that largely exercises this code.)
> feat: add support for deferring upstream artifact selection until runtime

- HISTORY.rst
#644 merged after the version bump, but before we tagged for 60.1.0; may as well include it.
> Update 60.1.0 changelog to include deferring upstream artifact selection until runtime

- setup.py
The pypi-publish action refuses to run to completion without this:
```
Checking dist/scriptworker-60.1.0-py2.py3-none-any.whl: FAILED
ERROR    `long_description` has syntax errors in markup and would not be
rendered on PyPI.
No content rendered from RST source.
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.
Checking dist/scriptworker-60.1.0.tar.gz: PASSED with warnings
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.
WARNING  `long_description` missing.
```
> fix: Add long_description

- src/scriptworker/client.py
- src/scriptworker/context.py
- src/scriptworker/cot/verify.py
- src/scriptworker/utils.py
- src/scriptworker/worker.py
- tests/conftest.py
- tests/test_integration.py
- tests/test_production.py
Add scriptworker.utils.scriptworker_session to create our aiohttp ClientSession objects in a single place.
Fixes #660
> feat: set User-Agent in our http requests

- .taskcluster.yml
Avoid re-running CI on irrelevant events on PRs.
> ci: filter pull-request events

- src/scriptworker/constants.py
- src/scriptworker/cot/verify.py
- src/scriptworker/task.py
- tests/test_cot_verify.py
- tests/test_task.py
Tasks like dep-signing in untrusted pull requests want to verify chain-of-trust.  This change allows github-pull-request-untrusted for the "mobile" trust domain.
> Bug 1906748: support github-pull-request-untrusted in CoT verification

- src/scriptworker/cot/verify.py
- tests/test_cot_verify.py
This is a bustage fix from https://bugzilla.mozilla.org/show_bug.cgi?id=1903776, which AFAICT will break CoT verification for anything run off of a cron task.
> fix: pull project from the default branch in projects.yml

- .taskcluster.yml
Anything else should route through a PR. If we need other long lived branches in the future we can add them, and also add them to https://github.com/mozilla-releng/fxci-config/blob/main/projects.yml.
> ci: for pushes, only run taskcluster on main

- HISTORY.rst
- src/scriptworker/version.py
- version.json
Arguably the projects.yml changed could make this 61.0.0? Except that major change is in another repo. I can do a major bump here if anyone cares.
> chore: version bump scriptworker 60.2.0

- tests/test_context.py
temp_queue downloads were reverted in 32.0.2, and while the test was partially kept, it didn't do anything, which was made obvious by https://github.com/python/cpython/issues/100690, when the call to `called_once_with` started raising.
> E               AttributeError: 'called_once_with' is not a valid assertion. Use a spec for the mock if 'called_once_with' is meant to be an attribute.. Did you mean: 'assert_called_once_with'?
> tests: remove broken temp_queue test

- tests/test_production.py
This test was added in https://github.com/mozilla-releng/scriptworker/pull/594 and depends on an indexed task that is not run by any automation, which means it will always expire and cause bustage.
> remove adhoc-signing test that will inevitably break

- src/scriptworker/constants.py
This repository was renamed, and the source_env_prefix we use in `.taskcluster.yml` is derived from the repo name. We need to update this to match, as well as update the repo name itself.
> fix: update translations repo in constants

- src/scriptworker/log.py
- tests/test_log.py
Avoid deadlock with full pipe buffer when the output contains long lines (>64kB).  If we go this long without a newline, log what we have and keep going.
> Bug 1941166 - handle long lines in pipe_to_log

- src/scriptworker/constants.py
...so that we can test L3 signing there without complaints.
This probably should've been done with https://github.com/mozilla-releng/scriptworker/commit/2296f2509ed011e18ec25f3a31f80b0e4106eeba
> bug 1944603: fix: add maple to all-nightly-branches

- tests/test_utils.py
Multiple instances of "F824 `global retry_count` is unused: name is never assigned in scope"
> tests: fix new pyflakes error

- taskcluster/kinds/docker-image/kind.yml
- taskcluster/kinds/tox/kind.yml
- tox.ini
- use pip instead of setup.py develop in tox, the latter is deprecated /
broken in newer pythons
- fix py310-cot tox env to actually run the cot tests
> ci: add python 3.12 and 3.13

- src/scriptworker/worker.py
- tests/test_worker.py
SIGTERM handling was originally added in https://github.com/mozilla-releng/scriptworker/pull/310. There is a [conversation thread](https://github.com/mozilla-releng/scriptworker/pull/310#discussion_r253707819) there about not uploading artifacts other than logs, but doesn't have any strong justification for this behaviour:
* "I think that the potentially-incomplete/corrupt artifacts won't have much value"
* "it [uploading files before being killed] becomes tougher"
I don't think either of these hold true at this point. I have a very strong use case for uploading non-log files in https://bugzilla.mozilla.org/show_bug.cgi?id=1967787 (making it trivial to find lando job status in a rerun). We've also proven out in other contexts that we can uploading 10s of gigabytes from a GCE instance to …
> feat: upload all artifacts even when SIGTERM is received

- setup.py
- tox.ini
Caused by the recent pytest-asyncio 1.0 release, which included https://github.com/pytest-dev/pytest-asyncio/pull/1106.
We need to pin to <1.0 until we upgrade all scriptworkers past python 3.8, I guess.
> fix: test failures around missing 'event_loop' fixture

- HISTORY.rst
- requirements.txt
- src/scriptworker/version.py
- tox.ini
- version.json
3.12.9 contains the fix for
https://github.com/aio-libs/aiohttp/issues/11138 which caused our OoM issues on artifacts upload.
Unfortunately we cannot repin to >=3.12.9  because it doesn't support python 3.8, that should be fine as it should always take the latest version but it's something to keep in mind if someone's doing partial dependency updates
> Repin aiohttp to >= 3 and bump version to 60.10.2

- src/scriptworker/worker.py
Sometimes the worker takes so long to start that it's already been told to shut off before it sets its signal handlers which leads to the worker continuing as if everything's going well. To combat that, we want to send the USR1 signal in a loop instead of assuming that the worker has already received it. Receiving said signal is idempotent so it shouldn't be an issue but we don't want it to spam the logs if possible
> Bug 1975771 - Don't spam logs if we continue receiving SIGUSR1

- tests/test_artifacts.py
Let the test pass immediately instead of waiting up to 15 seconds.
> tests: don't sleep in download timeout test
